name: Test WP Engine GHA
on:
  push:
    branches:
     - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Lint yml files
      uses: actions/checkout@v3
    - run: echo "Running yamllint!"
    - run: shellcheck entrypoint.sh
